name: Iceaxe-CI-Javadoc

on: [workflow_dispatch, workflow_call]

jobs:
  Prepare:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    defaults:
      run:
        shell: bash
    env:
      JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8

    steps:
      - name: Setup_Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build_Javadoc
        run: |
         ./gradlew -i clean iceaxe-core:javadoc --warning-mode all

      - name: Publish_Javadoc
        uses: actions/upload-pages-artifact@v3
        with:
          path: modules/iceaxe-core/build/docs/javadoc

  Deplpy:
    needs: Prepare
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    timeout-minutes: 30

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
